Repository pipeseroni/pipes.sh, pull requests merged in 2018-02, with the labels that each got.

#20 Reduced randomness
  README.rst
  pipes.sh
Labels: merge

#42 add keyboard controls
  README.rst
  doc/pipes.sh.6
  pipes.sh
Labels: enhancement

#48 improve issue templates readability, require $TERM info, add fenced code example
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/BUG.md
Labels: enhancement

#49 Break code into functions and add comments on variables
  pipes.sh
Labels: enhancement

#50 update manpage, add history section to README (close #41)
  README.rst
  pipes.sh.6
Labels: bug, enhancement
